export const hotelTypes = [
  "Budget",
  "Boutique",
  "Luxury",
  "Ski Resort",
  "Business",
  "Eco-Friendly",
  "All-Inclusive",
  "Hostel",
  "Bed and Breakfast",
  "Extended Stay",
  "Resort",
  "Vacation Rental",
  "Capsule",
  "Family",
  "Spa",
  "Historic",
  "Adult Only",
  "Beachfront",
  "Casino",
  "Pet-Friendly",
  "Apartment",
  "Villas",
  "Heritage",
  "Farm Stay",
  "Mountain Lodge",
  "Golf Resort",
  "Airport",
  "Camping/Glamping",
  "Chalet",
  "Convention",
  "Wellness Retreat",
  "Waterfront",
  "Adventure",
  "Cruise",
  "Ranch",
  "Motels",
  "Holiday Park",
  "Homestay",
  "Treehouse",
  "Floating",
  "Desert",
].sort();

export const hotelFacilities = [
  "Free Wifi",
  "Swimming Pool",
  "Fitness Center",
  "Spa and Wellness Center",
  "Restaurant",
  "Bar/Lounge",
  "Room Service",
  "Free Parking",
  "Airport Shuttle",
  "Pet-Friendly",
  "Laundry Service",
  "24-Hour Front Desk",
  "Business Center",
  "Meeting Rooms",
  "Concierge Service",
  "Non-Smoking Rooms",
  "Air Conditioning",
  "Kitchenette",
  "Flat-Screen TV",
  "Mini Bar",
  "Coffee Maker",
  "Safe Deposit Box",
  "Balcony/Terrace",
  "Hot Tub",
  "Private Beach",
  "Children's Playground",
  "Babysitting Services",
  "Car Rental",
  "Luggage Storage",
  "Bicycle Rental",
  "Sauna",
  "Golf Course",
  "Tennis Court",
  "Casino",
  "Water Sports Facilities",
  "On-Site ATM",
  "Beauty Salon",
  "Conference Facilities",
  "EV Charging Station",
  "Game Room",
  "Library",
  "Sun Deck",
].sort();
